const fs= require("fs");
const http = require('http');

const server = http.createServer((req, res) => {
    // console.log(req.url);
    if (req.url == "/") {
        res.end("hello from ankit! It is very awesome");

    } else if (req.url == "/about") {
        res.end("hello from ankit! It is a ABOUTUS PAGE");
    } else if (req.url == "/contact") {
        res.end("hello from ankit! It is a CONTACTUS PAGE");
    } else if (req.url == "/userapi") {
        res.end("hello from ankit! It is a USERAPI PAGE");
        fstat.readFile(`${__dirname}/userAPI/userApi.json`,"utf-8",(err,data)=>{
            console.log(data);
            res.end(data);
        });
    }
    else {
        res.writeHead(404, { "content-type": "text/html" });
        res.end("<h1>This <<<error>>> is generated by me--Ankit.</h1>")
    };

});
server.listen(8000, "", () => {
    console.log("Listening to the port 8000");

});